### ISSUE TITLE
My program doestn't work. Help!

### ISSUE THREAD

**Issue by hocikeng** [hocikeng/legendary-robot#1]
#include <stdio.h>
#include <iostream>
using namespace std;
class troad
{
public:
int Width;
float Length;
troad();
troad(float length0, int width0);
};
troad::troad(float length0, int width0)
{
if (length0>0)
Length=length0;
else Length=1;
if (width0>0)
Width=width0;
else Width=1;
}
troad::troad()
{
Length=0;
Width=0;
}
int main()
{
troad road;
std::cout<<"Road Length = "<<road.length<<"\nRoad Width = "<<road.Width<<std::endl;
troad road1(50.5,4);
std::cout<<"Road Length = "<<road1.Length<<"\nRoad Width = "<<road1.Width<<std::endl;
return 0;
}

**Comment by hocikeng** [comment]
Thank you all guys, i already fixed it.

**Comment by Vladosetskii** [comment]
Бля друже я не успел тебе помочь. Зачем ты такой умный я мечтал помочь тебе

**Comment by outerVoid** [comment]
РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!
РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!
`РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!
РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!РУССКИЕ ВПЕРЕЁД!!!!!`
